# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/avdb/Documents/Reseau/projetReseau

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/avdb/Documents/Reseau/projetReseau

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/avdb/Documents/Reseau/projetReseau/CMakeFiles /home/avdb/Documents/Reseau/projetReseau/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/avdb/Documents/Reseau/projetReseau/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named create_socket

# Build rule for target.
create_socket: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 create_socket
.PHONY : create_socket

# fast build rule for target.
create_socket/fast:
	$(MAKE) -f CMakeFiles/create_socket.dir/build.make CMakeFiles/create_socket.dir/build
.PHONY : create_socket/fast

#=============================================================================
# Target rules for targets named sender

# Build rule for target.
sender: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sender
.PHONY : sender

# fast build rule for target.
sender/fast:
	$(MAKE) -f CMakeFiles/sender.dir/build.make CMakeFiles/sender.dir/build
.PHONY : sender/fast

#=============================================================================
# Target rules for targets named packet_interface

# Build rule for target.
packet_interface: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 packet_interface
.PHONY : packet_interface

# fast build rule for target.
packet_interface/fast:
	$(MAKE) -f CMakeFiles/packet_interface.dir/build.make CMakeFiles/packet_interface.dir/build
.PHONY : packet_interface/fast

#=============================================================================
# Target rules for targets named read_write_receiver

# Build rule for target.
read_write_receiver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 read_write_receiver
.PHONY : read_write_receiver

# fast build rule for target.
read_write_receiver/fast:
	$(MAKE) -f CMakeFiles/read_write_receiver.dir/build.make CMakeFiles/read_write_receiver.dir/build
.PHONY : read_write_receiver/fast

#=============================================================================
# Target rules for targets named receiver

# Build rule for target.
receiver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 receiver
.PHONY : receiver

# fast build rule for target.
receiver/fast:
	$(MAKE) -f CMakeFiles/receiver.dir/build.make CMakeFiles/receiver.dir/build
.PHONY : receiver/fast

#=============================================================================
# Target rules for targets named wait_for_client

# Build rule for target.
wait_for_client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wait_for_client
.PHONY : wait_for_client

# fast build rule for target.
wait_for_client/fast:
	$(MAKE) -f CMakeFiles/wait_for_client.dir/build.make CMakeFiles/wait_for_client.dir/build
.PHONY : wait_for_client/fast

#=============================================================================
# Target rules for targets named read_write_sender

# Build rule for target.
read_write_sender: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 read_write_sender
.PHONY : read_write_sender

# fast build rule for target.
read_write_sender/fast:
	$(MAKE) -f CMakeFiles/read_write_sender.dir/build.make CMakeFiles/read_write_sender.dir/build
.PHONY : read_write_sender/fast

#=============================================================================
# Target rules for targets named real_adress

# Build rule for target.
real_adress: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 real_adress
.PHONY : real_adress

# fast build rule for target.
real_adress/fast:
	$(MAKE) -f CMakeFiles/real_adress.dir/build.make CMakeFiles/real_adress.dir/build
.PHONY : real_adress/fast

#=============================================================================
# Target rules for targets named testCU

# Build rule for target.
testCU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testCU
.PHONY : testCU

# fast build rule for target.
testCU/fast:
	$(MAKE) -f CMakeFiles/testCU.dir/build.make CMakeFiles/testCU.dir/build
.PHONY : testCU/fast

src/create_socket.o: src/create_socket.c.o

.PHONY : src/create_socket.o

# target to build an object file
src/create_socket.c.o:
	$(MAKE) -f CMakeFiles/create_socket.dir/build.make CMakeFiles/create_socket.dir/src/create_socket.c.o
.PHONY : src/create_socket.c.o

src/create_socket.i: src/create_socket.c.i

.PHONY : src/create_socket.i

# target to preprocess a source file
src/create_socket.c.i:
	$(MAKE) -f CMakeFiles/create_socket.dir/build.make CMakeFiles/create_socket.dir/src/create_socket.c.i
.PHONY : src/create_socket.c.i

src/create_socket.s: src/create_socket.c.s

.PHONY : src/create_socket.s

# target to generate assembly for a file
src/create_socket.c.s:
	$(MAKE) -f CMakeFiles/create_socket.dir/build.make CMakeFiles/create_socket.dir/src/create_socket.c.s
.PHONY : src/create_socket.c.s

src/packet_implem.o: src/packet_implem.c.o

.PHONY : src/packet_implem.o

# target to build an object file
src/packet_implem.c.o:
	$(MAKE) -f CMakeFiles/packet_interface.dir/build.make CMakeFiles/packet_interface.dir/src/packet_implem.c.o
.PHONY : src/packet_implem.c.o

src/packet_implem.i: src/packet_implem.c.i

.PHONY : src/packet_implem.i

# target to preprocess a source file
src/packet_implem.c.i:
	$(MAKE) -f CMakeFiles/packet_interface.dir/build.make CMakeFiles/packet_interface.dir/src/packet_implem.c.i
.PHONY : src/packet_implem.c.i

src/packet_implem.s: src/packet_implem.c.s

.PHONY : src/packet_implem.s

# target to generate assembly for a file
src/packet_implem.c.s:
	$(MAKE) -f CMakeFiles/packet_interface.dir/build.make CMakeFiles/packet_interface.dir/src/packet_implem.c.s
.PHONY : src/packet_implem.c.s

src/read_write_receiver.o: src/read_write_receiver.c.o

.PHONY : src/read_write_receiver.o

# target to build an object file
src/read_write_receiver.c.o:
	$(MAKE) -f CMakeFiles/read_write_receiver.dir/build.make CMakeFiles/read_write_receiver.dir/src/read_write_receiver.c.o
.PHONY : src/read_write_receiver.c.o

src/read_write_receiver.i: src/read_write_receiver.c.i

.PHONY : src/read_write_receiver.i

# target to preprocess a source file
src/read_write_receiver.c.i:
	$(MAKE) -f CMakeFiles/read_write_receiver.dir/build.make CMakeFiles/read_write_receiver.dir/src/read_write_receiver.c.i
.PHONY : src/read_write_receiver.c.i

src/read_write_receiver.s: src/read_write_receiver.c.s

.PHONY : src/read_write_receiver.s

# target to generate assembly for a file
src/read_write_receiver.c.s:
	$(MAKE) -f CMakeFiles/read_write_receiver.dir/build.make CMakeFiles/read_write_receiver.dir/src/read_write_receiver.c.s
.PHONY : src/read_write_receiver.c.s

src/read_write_sender.o: src/read_write_sender.c.o

.PHONY : src/read_write_sender.o

# target to build an object file
src/read_write_sender.c.o:
	$(MAKE) -f CMakeFiles/read_write_sender.dir/build.make CMakeFiles/read_write_sender.dir/src/read_write_sender.c.o
.PHONY : src/read_write_sender.c.o

src/read_write_sender.i: src/read_write_sender.c.i

.PHONY : src/read_write_sender.i

# target to preprocess a source file
src/read_write_sender.c.i:
	$(MAKE) -f CMakeFiles/read_write_sender.dir/build.make CMakeFiles/read_write_sender.dir/src/read_write_sender.c.i
.PHONY : src/read_write_sender.c.i

src/read_write_sender.s: src/read_write_sender.c.s

.PHONY : src/read_write_sender.s

# target to generate assembly for a file
src/read_write_sender.c.s:
	$(MAKE) -f CMakeFiles/read_write_sender.dir/build.make CMakeFiles/read_write_sender.dir/src/read_write_sender.c.s
.PHONY : src/read_write_sender.c.s

src/real_address.o: src/real_address.c.o

.PHONY : src/real_address.o

# target to build an object file
src/real_address.c.o:
	$(MAKE) -f CMakeFiles/real_adress.dir/build.make CMakeFiles/real_adress.dir/src/real_address.c.o
.PHONY : src/real_address.c.o

src/real_address.i: src/real_address.c.i

.PHONY : src/real_address.i

# target to preprocess a source file
src/real_address.c.i:
	$(MAKE) -f CMakeFiles/real_adress.dir/build.make CMakeFiles/real_adress.dir/src/real_address.c.i
.PHONY : src/real_address.c.i

src/real_address.s: src/real_address.c.s

.PHONY : src/real_address.s

# target to generate assembly for a file
src/real_address.c.s:
	$(MAKE) -f CMakeFiles/real_adress.dir/build.make CMakeFiles/real_adress.dir/src/real_address.c.s
.PHONY : src/real_address.c.s

src/receiver.o: src/receiver.c.o

.PHONY : src/receiver.o

# target to build an object file
src/receiver.c.o:
	$(MAKE) -f CMakeFiles/receiver.dir/build.make CMakeFiles/receiver.dir/src/receiver.c.o
.PHONY : src/receiver.c.o

src/receiver.i: src/receiver.c.i

.PHONY : src/receiver.i

# target to preprocess a source file
src/receiver.c.i:
	$(MAKE) -f CMakeFiles/receiver.dir/build.make CMakeFiles/receiver.dir/src/receiver.c.i
.PHONY : src/receiver.c.i

src/receiver.s: src/receiver.c.s

.PHONY : src/receiver.s

# target to generate assembly for a file
src/receiver.c.s:
	$(MAKE) -f CMakeFiles/receiver.dir/build.make CMakeFiles/receiver.dir/src/receiver.c.s
.PHONY : src/receiver.c.s

src/sender.o: src/sender.c.o

.PHONY : src/sender.o

# target to build an object file
src/sender.c.o:
	$(MAKE) -f CMakeFiles/sender.dir/build.make CMakeFiles/sender.dir/src/sender.c.o
.PHONY : src/sender.c.o

src/sender.i: src/sender.c.i

.PHONY : src/sender.i

# target to preprocess a source file
src/sender.c.i:
	$(MAKE) -f CMakeFiles/sender.dir/build.make CMakeFiles/sender.dir/src/sender.c.i
.PHONY : src/sender.c.i

src/sender.s: src/sender.c.s

.PHONY : src/sender.s

# target to generate assembly for a file
src/sender.c.s:
	$(MAKE) -f CMakeFiles/sender.dir/build.make CMakeFiles/sender.dir/src/sender.c.s
.PHONY : src/sender.c.s

src/wait_for_client.o: src/wait_for_client.c.o

.PHONY : src/wait_for_client.o

# target to build an object file
src/wait_for_client.c.o:
	$(MAKE) -f CMakeFiles/wait_for_client.dir/build.make CMakeFiles/wait_for_client.dir/src/wait_for_client.c.o
.PHONY : src/wait_for_client.c.o

src/wait_for_client.i: src/wait_for_client.c.i

.PHONY : src/wait_for_client.i

# target to preprocess a source file
src/wait_for_client.c.i:
	$(MAKE) -f CMakeFiles/wait_for_client.dir/build.make CMakeFiles/wait_for_client.dir/src/wait_for_client.c.i
.PHONY : src/wait_for_client.c.i

src/wait_for_client.s: src/wait_for_client.c.s

.PHONY : src/wait_for_client.s

# target to generate assembly for a file
src/wait_for_client.c.s:
	$(MAKE) -f CMakeFiles/wait_for_client.dir/build.make CMakeFiles/wait_for_client.dir/src/wait_for_client.c.s
.PHONY : src/wait_for_client.c.s

tests/test.o: tests/test.c.o

.PHONY : tests/test.o

# target to build an object file
tests/test.c.o:
	$(MAKE) -f CMakeFiles/testCU.dir/build.make CMakeFiles/testCU.dir/tests/test.c.o
.PHONY : tests/test.c.o

tests/test.i: tests/test.c.i

.PHONY : tests/test.i

# target to preprocess a source file
tests/test.c.i:
	$(MAKE) -f CMakeFiles/testCU.dir/build.make CMakeFiles/testCU.dir/tests/test.c.i
.PHONY : tests/test.c.i

tests/test.s: tests/test.c.s

.PHONY : tests/test.s

# target to generate assembly for a file
tests/test.c.s:
	$(MAKE) -f CMakeFiles/testCU.dir/build.make CMakeFiles/testCU.dir/tests/test.c.s
.PHONY : tests/test.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... create_socket"
	@echo "... sender"
	@echo "... packet_interface"
	@echo "... read_write_receiver"
	@echo "... receiver"
	@echo "... rebuild_cache"
	@echo "... wait_for_client"
	@echo "... read_write_sender"
	@echo "... real_adress"
	@echo "... testCU"
	@echo "... src/create_socket.o"
	@echo "... src/create_socket.i"
	@echo "... src/create_socket.s"
	@echo "... src/packet_implem.o"
	@echo "... src/packet_implem.i"
	@echo "... src/packet_implem.s"
	@echo "... src/read_write_receiver.o"
	@echo "... src/read_write_receiver.i"
	@echo "... src/read_write_receiver.s"
	@echo "... src/read_write_sender.o"
	@echo "... src/read_write_sender.i"
	@echo "... src/read_write_sender.s"
	@echo "... src/real_address.o"
	@echo "... src/real_address.i"
	@echo "... src/real_address.s"
	@echo "... src/receiver.o"
	@echo "... src/receiver.i"
	@echo "... src/receiver.s"
	@echo "... src/sender.o"
	@echo "... src/sender.i"
	@echo "... src/sender.s"
	@echo "... src/wait_for_client.o"
	@echo "... src/wait_for_client.i"
	@echo "... src/wait_for_client.s"
	@echo "... tests/test.o"
	@echo "... tests/test.i"
	@echo "... tests/test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

